src/semantic-ui/DataList.js, src/semantic-ui/Selectize.js, stories/components/semantic-ui/Selectize.stories.js
This pull request refactors the Selectize component to correctly allow for the addition of new records.
=> Archnet #453 - New authority

package-lock.json, package.json, src/common/EditContainer.js, stories/components/semantic-ui/EditModal.stories.js
This pull request adds the `react-fast-compare` dependency and updates the EditContainer component to pass a `dirty` prop to the wrapped component. The value of the `dirty` prop will be `true` if the current state of the item does not match the original state.
=> Archnet #402 - Unsaved changes

src/semantic-ui/DataList.js, src/utils/Object.js
This pull request updates the `isFilterActive` logic in DataList in support of #319 for EVQ.
=> EVQ #319 - Text anchor

package-lock.json, package.json, src/index.js, src/semantic-ui/DropdownMenu.js, src/semantic-ui/RichTextArea.css, src/semantic-ui/RichTextArea.js
This pull request adds the RichTextArea and DropdownMenu components in support of #318 for EVQ. See [this](https://github.com/artshumrc/evq/pull/327) PR in EVQ repo.
=> EVQ #318 - Static pages

README.md
Adding documentation on publishing process to README.md.
=> RC #131 - Publishing documentation

packages/semantic-ui/src/components/LoginModal.js, packages/storybook/src/semantic-ui/LoginModal.stories.js
This pull request provides the ability to hide the Cancel button on the LoginModal component.
=> RC #139 - Login Modal

packages/shared/src/index.js
This pull request exports the Hooks class from the shared-components `index.js`.
=> RC #149 - Hooks

packages/semantic-ui/package.json, packages/semantic-ui/src/components/LazyDocument.css, packages/semantic-ui/src/components/LazyDocument.js, packages/semantic-ui/src/components/LazyVideo.js, packages/storybook/src/semantic-ui/LazyDocument.stories.js, packages/storybook/src/semantic-ui/LazyVideo.stories.js, yarn.lock
This pull request adds automatically generated previews to the LazyDocument and LazyVideo components. Previews can still be supplied manually using the `preview` prop.
=> IIIF #5 - Resources

packages/semantic-ui/src/components/ReferenceCodeFormDropdown.js, packages/semantic-ui/src/components/ReferenceCodeFormLabel.js, packages/semantic-ui/src/i18n/en.json, packages/semantic-ui/src/index.js, packages/shared/src/index.js, packages/shared/src/services/ReferenceTables.js, packages/shared/src/transforms/References.js, packages/storybook/.storybook/middleware.js, packages/storybook/.storybook/routes/ControlledVocabulary.js, packages/storybook/src/semantic-ui/ReferenceCodeDropdown.stories.js, packages/storybook/src/semantic-ui/ReferenceCodeFormDropdown.stories.js, packages/storybook/src/semantic-ui/ReferenceCodeFormLabel.stories.js
This pull request adds the ReferenceCodeFormDropdown component, which will allow editing a reference table directly from the field that is using it.
=> UDCSL #28 - Media

packages/semantic-ui/package.json, packages/semantic-ui/src/components/DatePicker.css, packages/semantic-ui/src/components/ItemCollection.js, packages/semantic-ui/src/components/ReferenceCodeDropdown.js, packages/semantic-ui/src/components/ReferenceCodeFormLabel.css, packages/semantic-ui/src/components/ReferenceCodeFormLabel.js, packages/semantic-ui/webpack.config.js, packages/shared/package.json, packages/shared/src/components/InfiniteScroll.js, packages/shared/src/utils/Date.js, packages/storybook/src/semantic-ui/DatePicker.stories.js, packages/storybook/src/semantic-ui/ItemCollection.stories.js, packages/storybook/src/semantic-ui/ReferenceCodeDropdown.stories.js, packages/webpack/index.js, packages/webpack/package.json
This pull request fixes a bug in the ReferenceCodeDropdown component where selected items were not being properly marked for deletion.
=> UDCSL #46 - Projects

README.md, lerna.json, package.json, react-components.json, scripts/publish.js, yarn.lock
This pull request creates a script to automate publishing the `shared-components` and `semantic-components` packages to NPM.
=> RC #160 - Publishing script

.eslintrc.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/storybook/src/visualize/TreeGraph.stories.js, packages/visualize/LICENSE, packages/visualize/index.js, packages/visualize/package.json, packages/visualize/src/components/TreeGraph.css, packages/visualize/src/components/TreeGraph.js, packages/visualize/src/hooks/Zoom.css, packages/visualize/src/hooks/Zoom.js, packages/visualize/src/i18n/en.json, packages/visualize/src/i18n/i18n.js, packages/visualize/src/index.js, packages/visualize/webpack.config.js, react-components.json, yarn.lock
This pull request creates the `visualize` package, as well as the TreeGraph component used [here](https://github.com/performant-software/urban-design-csl/pull/66).
=> UDCSL #63 - Project graph

packages/semantic-ui/package.json, packages/shared/package.json, packages/visualize/package.json, react-components.json
=> UDCSL #63 - Publishing v0.6.0

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/README.md, packages/user-defined-fields/package.json, packages/user-defined-fields/src/components/UserDefinedFieldModal.js, packages/user-defined-fields/src/components/UserDefinedFieldsForm.js, packages/user-defined-fields/src/i18n/en.json, packages/user-defined-fields/src/index.js, packages/user-defined-fields/src/transforms/Fieldable.js, packages/user-defined-fields/src/transforms/UserDefinedField.js, packages/user-defined-fields/src/transforms/UserDefinedFields.js, packages/user-defined-fields/src/utils/UserDefinedFields.js, packages/visualize/package.json, react-components.json
This pull request makes the following changes to the user-defined-fields package:
- Updates the UserDefinedFieldsForm component to store date strings in ISO8601 format
- Removes the `resolveValue` function from the utility class
- Adds the Fieldable transform for sending the `user_defined` property on API requests
- Adds the `searchable` attribute to the UserDefinedField/UserDefinedFields transforms
**Note:** This pull request also contains the changes in [#6](https://github.com/performant-software/react-components/pull/169).
=> UDF #3 - Search/sort

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/package.json, packages/user-defined-fields/src/components/UserDefinedFieldsForm.js, packages/visualize/package.json, react-components.json
This pull request updates the UserDefinedFieldsForm component to accept a `tableName` prop and passes it on the request to the `/user_defined_fields` API endpoint.
=> UDF #21 - Table filter

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/shared/src/components/IIIFViewer.js, packages/shared/src/components/RichTextArea.js, packages/shared/src/hooks/Suspense.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request updates the IIIFViewer and RichTextArea components to lazy import specific dependencies in order to support server side rendering.
=> UDCSL #77 - Public website setup

.flowconfig, packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/Draggable.js, packages/semantic-ui/src/components/HorizontalCards.js, packages/semantic-ui/src/components/Selectize.js, packages/semantic-ui/src/components/SelectizeImageHeader.css, packages/semantic-ui/src/components/SelectizeImageHeader.js, packages/semantic-ui/src/i18n/en.json, packages/semantic-ui/src/index.js, packages/shared/package.json, packages/storybook/src/hooks/Images.js, packages/storybook/src/semantic-ui/HorizontalCards.stories.js, packages/storybook/src/semantic-ui/Selectize.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request updates the HorizontalCards component to support drag and drop (and also the Draggable component to support horizontal drag and drop).
This pull request also updates the Selectize component to support a custom render function.
This pull request also adds the SelectizeImageHeader component.
=> UDCSL #87 - CMS fields

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/storybook/src/visualize/TreeGraph.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, packages/visualize/src/components/TreeGraph.js, packages/visualize/src/hooks/Zoom.css, react-components.json
This pull request adjusts the TreeGraph component to allows the consuming application to render nodes via HTML instead of SVG rectangles/circles using the `foreignObject` element.
=> UDCSL #92 - Project people

packages/controlled-vocabulary/package.json, packages/controlled-vocabulary/src/components/ReferenceCodeDropdown.js, packages/semantic-ui/package.json, packages/semantic-ui/src/components/DataList.js, packages/semantic-ui/src/components/FileUploadModal.js, packages/semantic-ui/src/components/FilterLabels.css, packages/semantic-ui/src/components/FilterLabels.js, packages/semantic-ui/src/components/List.css, packages/semantic-ui/src/components/List.js, packages/semantic-ui/src/components/ListFilters.js, packages/semantic-ui/src/i18n/en.json, packages/semantic-ui/src/index.js, packages/shared/package.json, packages/storybook/src/semantic-ui/ListTable.modules.js, packages/storybook/src/semantic-ui/ListTable.stories.mdx, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request modifies the behavior of the `filters` configuration prop for the `DataList` component.
```
const MyComponent = () => {
...
};
export default useDataList(MyComponent);
```
```
<MyComponent
...
filters={{
component: ListFilters,
defaults: {
filters: [{
key: 'admin_access',
operator: 'equal',
value: true
}]
},
props: {
filters: [{
attributeName: 'admin_access',
key: 'admin_access',
label: 'Admin access',
type: 'boolean'
}]
}
}}
/>
```
This pull request also adds the `FilterLabels` component, which will display labels of applied filters in the list header if passed as `true`.
=> UDCSL #190 - Default filters

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/FileUploadModal.js, packages/shared/package.json, packages/user-defined-fields/package.json, packages/user-defined-fields/src/components/UserDefinedFieldsEmbeddedList.js, packages/user-defined-fields/src/components/UserDefinedFieldsList.js, packages/user-defined-fields/src/i18n/en.json, packages/user-defined-fields/src/utils/UserDefinedFields.js, packages/visualize/package.json, react-components.json
This pull request updates the UserDefinedFieldsList and UserDefinedFieldEmbeddedList to set the default value for the `order` input element. The value is required to be numeric and will result in an error if `null` or `undefined`.
It also adjusts the `resolveErrors` utility function to handle field errors.
Lastly, this pull request adds client side validation for user defined field order.
=> UDCSL #202 - User defined field errors

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/CurrentFacetLabels.js, packages/semantic-ui/src/components/SearchBox.js, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request fixes a bug in the SearchBox component, where the onKeyUp prop was not correctly providing a function.
=> BASIRA #193 - Pagination

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/ImageCarousel.css, packages/semantic-ui/src/components/ImageCarousel.js, packages/semantic-ui/src/components/LazyDocument.css, packages/semantic-ui/src/components/LazyDocument.js, packages/semantic-ui/src/components/LazyImage.css, packages/semantic-ui/src/components/LazyImage.js, packages/semantic-ui/src/components/LazyVideo.css, packages/semantic-ui/src/components/LazyVideo.js, packages/semantic-ui/src/index.js, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request updates the LazyDocument, LazyImage, and LazyVideo components to hide the `img` element until fully loaded. In order to make the request for the image, the element must be in the DOM, but not necessarily visible to the user.
This pull request also adds the ImageCarousel component.
=> BASIRA #195 - Search thumbnails

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
Republishing v1.0.16 as v1.0.17 due to a merge/publish issue.
=> BASIRA #208 - Navigation

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/SearchResultsSort.js, packages/semantic-ui/src/index.js, packages/semantic-ui/src/types/InstantSearch.js, packages/shared/package.json, packages/storybook/src/semantic-ui/SearchResultsSort.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request adds the SearchResultsSort component to allow sorting Instant Search indexes by dynamic values.
**Note:** This pull request also contains the changes in #195.
=> BASIRA #234 - Search sort

packages/semantic-ui/src/components/PlayButton.js, packages/storybook/src/semantic-ui/PlayButton.stories.js
This PR adds documentation and stories for the `PlayButton` component, closing #205
=> Add docs and stories for PlayButton

packages/semantic-ui/src/components/SaveButton.js, packages/storybook/src/semantic-ui/SaveButton.stories.js
- Added commenting into the `SaveButton.js` component to provide some (minimal) documentation;
- Added Storybook stories for the SaveButton component.
=> Updates to SaveButton docs and story

.gitignore, packages/semantic-ui/src/components/Toaster.js, packages/storybook/src/semantic-ui/Toaster.stories.js
This adds documentation of the Props and create a few Storybook stories to show usage.
=> Stories and documentation for the Toaster component

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/ItemsToggle.js, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull requests adds the `basic` and `sortColor` props to the ItemsToggle higher-order component.
=> CDC #19 - Layout

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/FacetSlider.js, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request fixes a bug in the visibility logic on the FacetSlider component.
=> BASIRA #246 - Date facet

packages/controlled-vocabulary/package.json, packages/geospatial/package.json, packages/geospatial/src/components/MapDraw.css, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request overrides the style from the `@mapbox/mapbox-gl-draw` library to set the `height` of the `mapboxgl-children` element to "0". Without this, the element height is set to "100%" and will block any elements below it.
=> CDC #104 - MapDraw

packages/controlled-vocabulary/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/package.json, packages/user-defined-fields/src/components/UserDefinedFieldsEmbeddedList.js, packages/user-defined-fields/src/components/UserDefinedFieldsList.js, packages/user-defined-fields/src/i18n/en.json, packages/visualize/package.json, react-components.json
This pull request adds the `uuid` attribute to the UserDefinedFieldsEmbeddedList and UserDefinedFieldsList components.
=> CDC #152 - Reset Manifests

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/AssociatedDropdown.js, packages/shared/package.json, packages/storybook/src/semantic-ui/AssociatedDropdown.stories.js, packages/storybook/src/user-defined-fields/UserDefinedFieldsEmbeddedList.stories.js, packages/user-defined-fields/package.json, packages/user-defined-fields/src/components/UserDefinedFieldsEmbeddedList.js, packages/user-defined-fields/src/components/UserDefinedFieldsList.js, packages/visualize/package.json, react-components.json
This pull request adds the ability to add arbitrary buttons to the AssociatedDropdown component. It also adds the ability to customize the actions displayed on the UserDefinedFieldsList and UserDefinedFieldsEmbeddedList components.
=> CDC #204 - Related Records

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/List.js, packages/shared/package.json, packages/shared/src/utils/Object.js, packages/user-defined-fields/package.json, packages/user-defined-fields/src/hooks/UserDefinedFields.js, packages/user-defined-fields/src/index.js, packages/visualize/package.json, react-components.json
This pull request makes the following changes in support of the [merge records](https://github.com/performant-software/core-data-cloud/issues/205) feature for Core Data:
- Adds the `userDefinedFields` array as a return value in the `useUserDefinedColumns` hook
- Updates the "Add" button to display in the `List` component even if the list is selectable
- Adds the `without` utility function to remove a specified attribute from a nested object
=> CDC #205 - Merge Records

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/FileUploadModal.js, packages/shared/package.json, packages/user-defined-fields/package.json, packages/user-defined-fields/src/components/UserDefinedFieldsForm.js, packages/user-defined-fields/src/index.js, packages/user-defined-fields/src/types/UserDefinedField.js, packages/visualize/package.json, react-components.json
This pull request makes the following changes:
- Adds the `errors`, `itemComponentProps`, and `onValidate` props to the `FileUploadModal` component
- Adds the `fields` and `required` props to the `UserDefinedFieldsForm` component
- If the `fields` prop is provided, an additional API call to load the fields will not be executed
- If the `required` prop is provided, only required fields will be displayed on the form
=> CDC #237 - Image Upload

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/geospatial/src/components/MapDraw.js, packages/semantic-ui/package.json, packages/shared/package.json, packages/storybook/src/geospatial/MapDraw.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull requests adds `cooperativeGestures`, `fullscreen`, and `navigation` props to the MapDraw component.
=> CDC #240 - Place Edit Form

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/core-data/src/services/BaseService.js, packages/core-data/src/utils/Api.js, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request fixes a bug with multiple project ID values being sent to the Core Data API.
=> RC #293 - Project IDs

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/DataTable.js, packages/semantic-ui/src/components/Items.js, packages/semantic-ui/src/components/List.js, packages/semantic-ui/src/i18n/en.json, packages/shared/package.json, packages/storybook/src/semantic-ui/DataTable.stories.js, packages/storybook/src/semantic-ui/Items.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request updates the `Items` and `DataTable` components to accept `as` and `asProps` props for the `actions` props.
=> CDC #302 - Link related media

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/DataTable.js, packages/semantic-ui/src/components/EmbeddedList.js, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request adds the element index on the action `onClick` attribute in the `DataTable` component. It also updates the `EmbeddedList` component to accept a `tableProps` prop, which will be passed through to `DataTable`.
=> CDC #271 - Import Modal Sort

package.json, packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/shared/src/utils/Object.js, packages/shared/test/utils/Object.spec.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json, yarn.lock
This pull request updates the `Object#isEqual` function to include a `removeEmpty` option for `object` types. When `true`, any key with a value that matches one of the `emptyValues` option will be removed from the object before checking for equality.
=> CDC #292 - Import Compare

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/FacetSlider.js, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request fixes a bug in the `FacetSlider` component where the component was not visible if either the min or max value was "0".
=> BASIRA #254 - Slider facets

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/FacetSlider.css, packages/semantic-ui/src/components/FacetSlider.js, packages/shared/package.json, packages/storybook/src/semantic-ui/FacetSlider.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request adds the ability to provide the `editable` prop to the FacetSlider component to allow the min/max values to be input manually.
=> BASIRA #257 - Date facet input

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
=> Publishing v2.2.19

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/Facet.js, packages/semantic-ui/src/components/FacetList.css, packages/semantic-ui/src/components/FacetList.js, packages/shared/package.json, packages/storybook/src/semantic-ui/FacetList.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request adds the ability to pass a `renderLabel` prop to the FacetList component to customize item rendering. It also adds the ability to pass a `onActive` callback function to the Facet prop to fired whenever the facet becomes active.
=> BASIRA #290 - Facet tooltip

packages/core-data/src/components/FacetListsGrouped.js, packages/core-data/src/components/FacetStateContextProvider.js
This pull request adds the `include` and `exclude` props to the FacetStateContextProvider component to allow the consumer to customize the available facets.
It also updates the FacetListsGrouped component to group facets by ID or label values.
=> CDP #23 - Facets show more

packages/core-data/src/components/Pill.js, packages/core-data/src/index.js, packages/storybook/src/core-data/Pill.stories.js
This PR adds the `Pill` component from #331.
=> Core Data Pill component

packages/core-data/src/components/Checkbox.js, packages/core-data/src/index.js, packages/storybook/src/core-data/Checkbox.stories.js
This PR adds the Checkbox component from #329 
https://github.com/user-attachments/assets/ba94dcde-f558-4fc1-8e72-ce26a284dfe7
=> `Checkbox` component

packages/core-data/src/components/RecordDetailHeader.js
Re-checks whether to display a `Show More` button in the `RecordDetailHeader` when the height of the description content or its container changes.
=> `RecordDetailHeader`: Update showMore flag when div height changes

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request publishing v2.3.1.
=> CDP #76 - Reset button

packages/core-data/src/components/RecordDetailContent.js, packages/core-data/src/components/RecordDetailPanel.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js
This pull request fixes an issue in the RecordDetailPanel component where the "Show Less" button was sometimes visible without any content. This was happening when switching between records in the search view. The solution was to reset the "expanded" toggle when the `content` or `items` prop passed to `RecordDetailContent` was changed.
=> CDP #135 - Record detail panel

packages/core-data/src/utils/Peripleo.js, packages/core-data/src/utils/Typesense.js
This pull request updates Peripleo utils to handle the new configuration structure. It also adds the `connectionTimeout` and `timeout` options to pass to the Typesense adapter.
=> CDP #142 - Multisearch

packages/shared/src/utils/Object.js
This pull request adds `null` and falsey checking to the `Object#getNestedValue` function.
=> CDP #163 - Timeline visualization

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This PR bumps the version numbers for 2.3.15, which includes #490.
=> Publishing v2.3.15

packages/semantic-ui/src/components/LazyMedia.js, packages/semantic-ui/src/components/LazyVideo.js, packages/semantic-ui/src/components/MediaGallery.js, packages/semantic-ui/src/components/VideoPlayer.js, packages/shared/src/components/VideoTrack.js, packages/shared/src/index.js, packages/storybook/src/assets/test.vtt, packages/storybook/src/semantic-ui/LazyMedia.stories.js, packages/storybook/src/semantic-ui/LazyVideo.stories.js, packages/storybook/src/semantic-ui/MediaGallery.stories.js, packages/storybook/src/semantic-ui/VideoPlayer.stories.js
This pull request adds the `VideoTrack` component to the `shared` package and updates the `VideoPlayer` component to accept an optional prop for `transcriptions`, which will be used as video captions.
=> Archnet #1476 - Video captions

packages/core-data/package.json, packages/core-data/src/components/FacetTimeline.js, packages/core-data/src/components/Icon.js, packages/core-data/src/components/Notification.js, packages/core-data/src/components/Timeline.js, packages/core-data/src/index.js, packages/core-data/src/ssr.js, packages/storybook/src/core-data/Notification.stories.js, yarn.lock
This pull request makes the following changes in support of [#220](https://github.com/performant-software/core-data-places/issues/220):
Adds the `Notification` component to be used to alert the user of save actions.
Fixes an issue with the `Timeline` component where the zoom controls were positioned relative to the wrong parent element.
Changes the `FacetTimeline` default range color to `bg-primary`.
=> CDP #220 - Saved search results

packages/geospatial/src/components/LayerMenu.js, packages/semantic-ui/src/components/AssociatedDropdown.js, packages/semantic-ui/src/components/DataList.js, packages/semantic-ui/src/components/DataTable.js, packages/semantic-ui/src/components/DateInput.css, packages/semantic-ui/src/components/DateInput.js, packages/semantic-ui/src/components/Items.js, packages/semantic-ui/src/components/LazyImage.js, packages/semantic-ui/src/components/List.js, packages/semantic-ui/src/components/ListTable.js, packages/semantic-ui/src/components/LoginModal.js, packages/storybook/src/semantic-ui/ListTable.stories.js, packages/user-defined-fields/src/components/UserDefinedFieldsForm.js
This pull request mostly adds `key` props to child elements and default values to controlled input elements to prevent React warnings from displaying in the console.
=> CDC #457 - React warnings

packages/storybook/src/tailwind-ui/TextArea.stories.tsx, packages/tailwind-ui/src/components/TextArea.tsx, packages/tailwind-ui/src/index.ts
This PR includes the `TextArea` component for Performant UI.
It's built on top of Headless UI's `TextArea` component and is controlled with the standard `value` and `onChange` props like the other form components. It's very similar to `Input` so I used some of its classes as a starting point.
=> Performant UI `TextArea` component
