src/semantic-ui/NestedAccordion.js
It was discovered in https://github.com/performant-software/basira/issues/116 that when a `NestedAccordion` contains multiple types of objects, ID collisions may cause unexpected behaviors, such as with toggling.
To resolve this without breaking other implementations of `NestedAccordion`, this PR accepts a new boolean prop for that component called `multipleItemTypes`. When this prop is set `true`:
- `defaultActive` will expect an array of objects instead of an array of numbers. Each object in `defaultActive` is expected to have keys `id` and `type`. If any of this is not true, it will fall back to default behavior (i.e. as if `multipleItemTypes` were `false`)
- In `componentDidUpdate`, these objects will directly populate `activeItems` on the `NestedAccordion`'s state instead of using a …
=> BASIRA #116 - Allow multiple types in NestedAccordion

src/semantic-ui/FileUpload.js
For work in https://github.com/performant-software/basira/issues/113:
- `visible` prop: For some reason, without this, any error message will be clobbered when just using this component outside the context of a `FileUploadModal`. I guess some Semantic UI decision to prevent accidentally displaying messages in forms.
- `onSuccess` callback: This allows us to, for example, unmount this component when the validation was successful. If the validation threw errors, we can leave the component mounted and show the error messages.
=> BASIRA #113 - Use Message "visible" prop and add onSuccess callback in FileUpload

src/utils/Object.js
This pull request updates the ObjectUtils `isEqual` function to optionally ignore whitespace when comparing two string objects.
=> Archnet #587 - Unsaved changes

src/semantic-ui/DownloadButton.js, stories/components/semantic-ui/DownloadButton.stories.js
This pull request updates the DownloadButton component to use the standard browser download functionality, as opposed to the async Javascript implementation. This will eliminate the need for a loading indicator, as clicking the button will prompt the user to specify a location to download.
=> Archnet #600 - Download Button

src/common/EditContainer.js
This pull request updates the `resolveValidationError` prop in EditContainer to allow for a hash parameter, rather than individual arguments. This was done to add the `key` parameter, and no enforce any ordering of arguments.
This is a breaking change 💥 and will require documentation in the next release.
=> FCA #24 - Stripe API

src/semantic-ui/Selectize.js
This pull request fixes a bug in the Selectize component where the `selectedItems` prop was not correctly defaulting the value on the state.
=> Archnet #610 - Publication countries

src/semantic-ui/DataList.js, src/semantic-ui/TagsList.js, stories/components/semantic-ui/TagsList.stories.js
This pull request updates the DataList component to call a custom `onChange` prop nested in the `filters` prop in order to allow filters stored in the DataList to be used elsewhere. This is useful for EVQ in the public view where we have a list of annotations that are filterable (via DataList), but the filters also carry over to the reader interface.
=> EVQ #185 - Annotation filters

packages/shared/src/components/EditContainer.js
This pull request fixes a bug when opening an EditModal component via the ListTable.
The underlying EditContainer was using the named export `isEqual` from the `Object` class, which was changed to export a default object instead.
=> RC #146 - EditModal

packages/semantic-ui/src/components/AssociatedDropdown.js, packages/storybook/src/semantic-ui/AssociatedDropdown.stories.js
This pull request fixes a bug with using the "Add" button in the AssociatedDropdown component. When the ability to edit records via the AssociatedDropdown was added, it introduced a bug which made the "Add" button actually edit existing records if a value was selected.
The solution was to modify the logic to not provide an `id` value to the modal if the "Add" button was clicked.
=> EVQ #404 - Associated Dropdown

packages/semantic-ui/src/components/DataTable.js, packages/semantic-ui/src/components/EmbeddedList.js, packages/storybook/src/semantic-ui/EmbeddedList.stories.js
This pull request updates the EmbeddedList component to accept `defaultSort` and `defaultSortDirection` props in order to define how the list should be initially sorted:
```javascript
<EmbeddedList
columns={...}
defaultSort='created_at'
defaultSortDirection='descending'
/>
```
=> RC #153 - EmbeddedList default sort

packages/semantic-ui/src/components/KeyValuePairs.js, packages/semantic-ui/src/hooks/BatchEdit.js, packages/semantic-ui/src/i18n/en.json, packages/semantic-ui/src/index.js, packages/storybook/src/semantic-ui/KeyValuePairs.stories.js
This pull request creates the BatchEdit and KeyValuePair components, which will be used for rendering JSON fields with multiple keys/values in the Urban Design Case Study Library.
=> UDCSL #28 - Media

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/storybook/.storybook/routes/UserDefinedFields.js, packages/user-defined-fields/package.json, packages/user-defined-fields/src/components/UserDefinedFieldModal.js, packages/user-defined-fields/src/components/UserDefinedFieldsEmbeddedList.js, packages/user-defined-fields/src/components/UserDefinedFieldsForm.js, packages/user-defined-fields/src/components/UserDefinedFieldsList.js, packages/user-defined-fields/src/i18n/en.json, packages/user-defined-fields/src/transforms/UserDefinedField.js, packages/user-defined-fields/src/transforms/UserDefinedFields.js, packages/visualize/package.json, react-components.json
This pull request adds the `order` property to the user defined fields components. When fetching the user defined fields in the UserDefinedFieldsForm, results will be sorted by the `order`.
This pull request also fixes a bug where the fetch request in the UserDefinedFieldsForm was paginating the results.
The `order` input element has been added to the modal
The list has been updated to display the `order` for each field
The form will display inputs sorted by the `order`
=> UDF #23 - Field order

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/FileUploadModal.js, packages/semantic-ui/src/components/FileUploadProgress.css, packages/semantic-ui/src/components/FileUploadProgress.js, packages/semantic-ui/src/components/FileUploadStatus.css, packages/semantic-ui/src/components/FileUploadStatus.js, packages/semantic-ui/src/i18n/en.json, packages/shared/package.json, packages/storybook/src/semantic-ui/FileUploadModal.modules.js, packages/storybook/src/semantic-ui/FileUploadModal.stories.mdx, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request updates the `FileUploadModal` component to implement another strategy for uploading files. Previously, the component used a bulk upload strategy, which would send all files in a single request. Now, a `strategy` prop can be proved as `batch` (which will use the normal functionality) or `single`. The `single` strategy will create one request per file, and upload using the `onSave` prop. This will resolve issues where large numbers of files are being uploaded and connections are timing out after a certain amount of time.
Single strategy mode will display a progress bar
In single strategy mode, each file will display a status
=> IIIF #20 - File upload

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/shared/package.json, packages/shared/src/components/IIIFViewer.js, packages/shared/src/components/RichTextArea.css, packages/shared/src/components/RichTextArea.js, packages/shared/webpack.config.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request fixes an issue with the RichTextArea component not rendering. The issue happened when we updated the package to be SSR-friendly by lazy loading components that have dependencies that use browser objects (`window`, `document`, etc). We also updated the CSS to be imported by React's `lazy` function, which is intended to be used only for components.
The solution was to move the lazy function import out of the function, and move the CSS into the component CSS file loaded via webpack as normal.
This fix can be tested using `v1.0.8-beta.2`.
=> RC #180 - Rich Text Area

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/Facet.js, packages/semantic-ui/src/components/FacetList.js, packages/semantic-ui/src/components/FacetSlider.js, packages/semantic-ui/src/components/FacetToggle.js, packages/shared/package.json, packages/storybook/src/semantic-ui/Facet.stories.js, packages/storybook/src/semantic-ui/FacetList.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request implements the imperative `expand` and `collapse` functions for the Facet component. The motivation for this is to give parent components a way to control the `active` state without having to make the Facet component controlled.
**Note:** This pull request also contains the changes in #195 and #196.
=> BASIRA #230 - Expand/collapse facets

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/BreadcrumbItem.js, packages/semantic-ui/src/components/Breadcrumbs.css, packages/semantic-ui/src/components/Breadcrumbs.js, packages/semantic-ui/src/components/ItemsToggle.js, packages/semantic-ui/src/components/SimpleEditPage.css, packages/semantic-ui/src/components/SimpleEditPage.js, packages/semantic-ui/src/i18n/en.json, packages/semantic-ui/src/index.js, packages/shared/package.json, packages/shared/src/hooks/EditPage.js, packages/shared/src/index.js, packages/storybook/src/semantic-ui/Breadcrumbs.stories.js, packages/storybook/src/semantic-ui/SimpleEditPage.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request adds the following components:
- useEditPage - a wrapper for the `useEditContainer` hook, simplifying the onSave and validation
- SimpleEditPage - used to render an edit page with simple tab interface
- Breadcrumbs - Parses the URL and renders breadcrumbs as links
Fixes the following bugs:
- Fixes an issue in the ItemToggle component where the sort dropdown was being hidden when the view icon was hidden
=> CDC #2 - Projects

packages/semantic-ui/src/components/ListLoader.js, packages/storybook/src/semantic-ui/ListLoader.stories.js
This pull request adds documentation for the ListLoader component, which simply displays a spinner if active.
=> Add Storybook doc page for the ListLoader component

packages/semantic-ui/src/components/DateInput.css, packages/semantic-ui/src/components/DateInput.js, packages/storybook/src/semantic-ui/DateInput.stories.js
- Add props documentation, component comment, and stories for `DateInput`
- Update the prop type of `formatOptions` from `any` to `DateTimeFormatOptions`
- Fix a bug where the text input did not have enough right-padding to accommodate a right icon when there is also a left icon
- Note that I used the formula `(verticalPadding * 2) + glyphWidth` [from semantic-ui](https://github.com/Semantic-Org/Semantic-UI/blob/47acaa0ce4c8dcde6c76080483cf8a3566576770/src/themes/default/elements/input.variables#L35), which is how they end up with the crazy number `2.67142857em`
- This CSS could also be used for any other inputs that need both right and left icons, something that Semantic UI doesn't support out of the box
=> Add documentation and story for DateInput component

packages/controlled-vocabulary/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/EmbeddedList.js, packages/semantic-ui/src/components/FileUploadModal.js, packages/semantic-ui/src/components/ListTable.js, packages/semantic-ui/src/index.js, packages/shared/package.json, packages/shared/src/utils/Form.js, packages/storybook/src/user-defined-fields/UserDefinedFieldsEmbeddedList.stories.js, packages/storybook/src/user-defined-fields/UserDefinedFieldsList.stories.js, packages/user-defined-fields/package.json, packages/user-defined-fields/src/components/UserDefinedFieldsEmbeddedList.js, packages/user-defined-fields/src/components/UserDefinedFieldsList.js, packages/visualize/package.json, react-components.json
This pull request makes the following changes:
- Adds the `onComplete` prop to the FileUploadModal component which will fire the callback when the entire upload process is complete.
- Updates the UserDefinedFieldsList and UserDefinedFieldsEmbeddedList components to allow props for the underlying ListTable and EmbeddedList components.
- Fixes a bug in FormUtils where properties that don't exist on the object were being sent as `NULL` values. Now they will be omitted, which is consistent with the way we're serializing JSON payloads.
=> CDC #18 - Media

packages/controlled-vocabulary/package.json, packages/geospatial/package.json, packages/semantic-ui/package.json, packages/semantic-ui/src/components/AssociatedDropdown.js, packages/semantic-ui/src/components/DataTableColumnSelector.js, packages/semantic-ui/src/components/Items.js, packages/semantic-ui/src/components/ListTable.js, packages/shared/package.json, packages/storybook/src/semantic-ui/AssociatedDropdown.stories.js, packages/storybook/src/semantic-ui/EmbeddedList.stories.js, packages/storybook/src/semantic-ui/Items.stories.js, packages/storybook/src/semantic-ui/ListTable.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json
This pull request makes the following changes to support Core Data:
- Implements the `configureable` prop in DataTableColumnSelector
- Adds button customizations to AssociatedDropdown
- Adds the `itemsPerRow` prop to Items for grid view
- Adds action `size` customization to Items
=> CDC #60 - Data Entry Form

packages/core-data/src/components/PlaceMarkers.js
Update to PR #265 , but now using the updated `PlaceMarkers` component. Adds handling to filter out places passed to the component that have null `geometry` fields and thus run the risk of crashing the component.
When I tested this last week it seemed that the null geometry was handled somehow by the `feature` function imported from `@turf/turf`, but I must have misinterpreted that somehow because now it seems to be throwing a `coordinates must be a number` error. So hopefully this will fix that issue for real.
=> Fix placemarkers component to handle null geometry

packages/controlled-vocabulary/package.json, packages/core-data/package.json, packages/core-data/src/components/SearchResultsLayer.js, packages/geospatial/package.json, packages/geospatial/src/components/GeocodingControl.js, packages/geospatial/src/components/LocationMarkers.js, packages/geospatial/src/components/MapDraw.css, packages/geospatial/src/components/MapDraw.js, packages/geospatial/src/index.js, packages/geospatial/src/utils/Map.js, packages/semantic-ui/package.json, packages/shared/package.json, packages/storybook/src/geospatial/MapDraw.stories.js, packages/user-defined-fields/package.json, packages/visualize/package.json, react-components.json, yarn.lock
This pull request adds the GeocodingControl component and the `geocoding` prop to the MapDraw component. When set to "point" or "polygon", the map will render a search input that uses Map Tiler's geocoding API to lookup geometries by the entered place name. A value of "point" will add a lat/lng point to the map. A value of "polygon" will add a polygon outline of the location to the map.
=> CDC #121 - Geocoding

packages/core-data/src/utils/Typesense.js
- fixes #280 by changing the second index in `getFieldId`'s `substring` call to `value.length` instead of `value.length - 1`
=> Fix incorrect substring index in Core Data `getFieldId` helper function

packages/core-data/src/hooks/CoreData.js
- removes the `baseUrl` and `projectIds` arguments from the call to `onLoad` in the Core Data hook
- these were left over from a previous version of the package where these arguments had been required
Closes #279
=> Remove unneeded arguments from `onLoad` in Core Data hook

packages/core-data/src/types/RuntimeConfig.js, packages/core-data/src/utils/Peripleo.js, packages/core-data/src/utils/Typesense.js
Per #304 (see also performant-software/core-data-cloud#323):
- Allow users to set a default sort in the typesense configuration
- `_text_match:desc` is the default if no `sort_by` is passed; include that as the primary sort, then configured option as the secondary (i.e. the default sort if no text query is entered, and the tiebreaker for equivalent text matches)
- Are these the right places to set this? I basically just looked for wherever a typesense configuration was set.
- Is it ok to assume we just want an ascending sort on whatever field is passed to `default_sort`, or should the user have to specify direction?
- Should I publish a beta version in order to test this?
=> Allow default sort typesense configuration (#304)

packages/semantic-ui/src/components/DatetimeLocalInput.css, packages/semantic-ui/src/components/DatetimeLocalInput.js, packages/semantic-ui/src/index.js
Per performant-software/archnet3#1276:
- A new component in semantic-components called `DatetimeLocalInput` that uses the browser's native `datetime-local` picker, so that a user can input both a date _and_ a time.
- The consuming application will be responsible for handling formatting (it's ISO without the trailing `Z`) and timezone conversions.
- This input is available in [all major browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) as of 2021. However, there is one caveat: the calendar modal that pops up only allows picking dates, not times, in Firefox and Safari. But I think that should be fine, as you can still pick a time from the inline input in all browsers.
=> Archnet #1276 - Add DatetimeLocalInput

packages/geospatial/src/components/MapDraw.js
The `isValid` function in the `MapDraw` component checks whether the type of a given geometry object matches the type set by the `geocoding` prop. However, the vast majority of results actually have the `MultiPolygon` type (e.g. countries with little bits that aren't connected to the mainland or [the Kentucky Bend](https://en.wikipedia.org/wiki/Kentucky_Bend)), which caused `isValid` to incorrectly reject the geometry for most polygon search results.
Accepting either Polygon or MultiPolygon when `geometry='polygon'` allows the data to be written to the map as expected.
=> Add `MultiPolygon` support to `MapDraw`

packages/semantic-ui/src/components/LazyAudio.js, packages/semantic-ui/src/components/LazyDocument.js, packages/semantic-ui/src/components/LazyImage.js, packages/semantic-ui/src/components/LazyMedia.js, packages/semantic-ui/src/components/LazyVideo.js, packages/semantic-ui/src/i18n/en.json
Per performant-software/archnet3#1316:
- Update the button text to read "preview before upload" for viewing video/audio/image files before they have been uploaded to the server
- Hide download button for all files until they have been uploaded to the server
- Somewhat surprisingly to me, it seems detecting the presence of a local file in the browser (i.e. a url created by `URL.createObjectURL`) is as simple as checking that it begins with `blob:`. I can't test with Windows but this appears to be [defined in the File API spec](https://www.w3.org/TR/FileAPI/#url-intro).
- For video files, it looks like this across Mac Safari, Chrome, and FF:
And after saving the record and waiting for the data to be fetched:
Results are similar across other file types.
=> Archnet #1316 - Update preview label, disallow DL for blobs

packages/geospatial/package.json, packages/geospatial/src/components/MapDraw.js, yarn.lock
On Core Data, I was running into an issue where changing the `geocoding` prop had no effect on `MapDraw`'s behavior after first mount.
After a significant amount of investigation and experimentation, I was able to trace the issue to the fact that the `useControl`call in `GeocodingControl` relies on `useEffect` with an empty dependency array to update the geocoding settings, meaning the settings would never change even if the component's props changed.
My initial attempt to work around this issue by adding `key={props.geocoding}` to `GeocodingControl` (forcing it to re-mount when the geocoding prop changes) failed due to an odd bug in `@maptiler/geocoding-control` where the `MapTilerGeocoding` it created didn't properly clean itself up after being unmounted. Upgrading to a new version of …
=> Force `GeocodingControl` to rerender when geocoding type changes

packages/geospatial/src/components/GeocodingControl.css, packages/geospatial/src/components/GeocodingControl.js
This PR is an ugly fix for an issue where `@maptiler/geocoding-control/maplibregl`'s `GeocodingControl` component doesn't clean up its outermost container element on unmount, resulting in a new container spawning every time. Combined with the `key` re-mounting trick from #313, this means that the button slides down the page as the user toggles between modes.
These empty elements are visible because we're setting top/left margins on them via CSS. I would prefer to fix the issue at its root by making sure the elements get removed when `GeocodingControl` unmounts, but that seems to be the control's responsibility and we don't have a way to hook into it and do it ourselves. So in this PR I use the `:empty` selector to disable the margins on empty `.maplibregl-ctrl` elements, making them …
=> Hide empty leftover `GeocodingControl` container with CSS

packages/core-data/src/components/SearchResultsLayer.js, packages/core-data/src/utils/Typesense.js
- adds a new prop called `showPolygons`. When enabled, the component will prefer polygonal data over points. Points will still be displayed if there's no polygon data.
- updates the `toFeatureCollection` and `toFeature` functions in `TypesenseUtils` with a new, optional boolean param called `polygons`
=> Add `showPolygons` prop to `SearchResultsLayer`

packages/core-data/src/components/FacetTimeline.js, packages/core-data/src/components/HeaderImage.js, packages/core-data/src/components/KeyValueList.js, packages/core-data/src/components/PlaceDetails.js, packages/core-data/src/components/SearchResultsLayer.js, packages/core-data/src/hooks/CoreData.js, packages/core-data/src/hooks/ProgressiveSearch.js, packages/core-data/src/index.js, packages/core-data/src/services/Organizations.js, packages/core-data/src/utils/Typesense.js, packages/geospatial/src/components/LocationMarkers.js, packages/shared/src/index.js, packages/shared/src/utils/UserDefinedFields.js, packages/storybook/src/core-data/FacetTimeline.stories.js, packages/storybook/src/core-data/HeaderImage.stories.js, packages/storybook/src/core-data/KeyValueList.stories.js, packages/user-defined-fields/src/constants/DataTypes.js
This pull request updates the `core-data` package to work with any type of model, as opposed to just place records. These changes include:
- Removes the `useRange` prop from FacetTimeline in place of the `range`, `refine`, and `start` props
- Deprecates the `PlaceDetails` component and adds the `HeaderImage` and `KeyValueList` components
- Updates the `SearchResultsLayer` component to accept a `geometry` prop, which will be the path to the data that should be rendered on the map
- `coordinates`
- `<uuid>.geometry`
- Adds the missing `OrganizationsService` class
- Moves the user-defined fields `DataTypes` to the `shared` package; Adds a re-export in `user-defined-fields`
- This will allow handling of user-defined fields without the need to import the whole package, which has …
=> CDP #33 - Core data models

packages/shared/src/transforms/NestedAttributesTransform.js
Per performant-software/core-data-cloud#171:
- Prevent payload `order` attribute from being overwritten by array index in nested attributes transform
- see spread operator [overriding properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#overriding_properties)
=> Prevent order overwrite in nested attributes payload (CDC #171)

packages/core-data/src/components/Input.js, packages/core-data/src/index.js, packages/storybook/src/core-data/Input.stories.js, yarn.lock
This PR implements the `Input` component from #330.
I went with a regular `input` element instead of the Radix UI Form elements because it's tricky/annoying to deal with a Radix Form element like `Form.Input` outside of its `Form.Root`. When using in a Radix form, you can just:
```jsx
<Form.Input asChild>
<Input {...props} />
</Form.Input>
```
=> Add `Input` component

.github/workflows/storybook.yml
This PR adds a few lines to `storybook.yml` that should allow the build process in the workflow to read the environment variables stored in the repo.
=> Add Typesense environment variables to workflow

packages/core-data/src/components/Input.js
This PR addresses the bullet points in #347 by moving the focus outline to the entire component instead of just the interior `input` element, and setting the outline color to `primary`.
https://github.com/user-attachments/assets/b3a26b4f-446a-48bc-8797-ee167f12a9c2
=> Outline entire Input component on focus

packages/core-data/src/components/AccordionItemsList.js, packages/core-data/src/index.css, packages/core-data/src/index.js, packages/core-data/src/styles/AccordionItemsList.css, packages/storybook/src/core-data/AccordionItemsList.stories.js
Adds an accordion list component for displaying related record information in the record detail panel. See Figma: https://www.figma.com/design/5AWa1c3pJeVXwEeVPbRqZj/Place-Components-2.0?node-id=15-102&p=f&t=WW23fRNeoikc9Poz-0
I wasn't sure how granular to get in terms of what components we're exporting; it would be possible to factor out e.g. the `<Accordion.Item>` part as its own component, but since it needs to be inside an `<Accordion.Root>` tag in any case it felt neater to me to just have the whole accordion list as one entity. But I'm open to other thoughts about how to structure it.
=> Adding `AccordionItemsList` component

packages/core-data/src/components/Pagination.js, packages/core-data/src/components/SearchResultsTable.js, packages/storybook/src/core-data/SearchResultsTable.stories.js
This PR addresses Chelsea's feedback from #348 with the following changes:
* the component will now fill the height and width of its parent container
* the table itself scrolls horizontally and/or vertically if it doesn't fit in the width of its parent
* the header row is sticky-positioned to the top
* the pagination row is sticky-positioned to the bottom
https://github.com/user-attachments/assets/961aec23-0bf8-4308-bf7c-9bea9c0671d1
=> SearchResultsTable overflow behavior

packages/core-data/src/components/RecordDetailItem.js, packages/storybook/src/core-data/RecordDetailItem.stories.js
Adds a utility component for rendering the values of Core Data fields on the record detail panel, including optional icons. See https://www.figma.com/design/5AWa1c3pJeVXwEeVPbRqZj/Place-Components-2.0?node-id=84-1209&m=dev
Note: Should be merged after PR #353
=> Adding record detail item component

packages/core-data/src/components/RecordDetailHeader.js, packages/core-data/src/i18n/en.json, packages/storybook/src/core-data/RecordDetailHeader.stories.js
Adds the `RecordDetailHeader` component for use in the record detail panel. The blurb is passed as a child node and thus preserves flexibility about exactly how it is rendered, e.g. from a rich text field in Core Data. The component takes an optional url prop; if provided, it will display a `View Details` button linking to the given url.
(The breadcrumb navigation and functionality such as `onClose` behavior will belong to the parent panel component, and so those elements are not included here.)
Note: This should be merged after PR #355 and PR #356
=> Adding RecordDetailHeader component

packages/core-data/src/components/RecordDetailBreadcrumbs.js, packages/storybook/src/core-data/RecordDetailBreadcrumbs.stories.js
Adds a breadcrumb navigation component for use in the record detail modal, which optionally accepts a function to be called when the back arrow is clicked.
=> Adding breadcrumb component for record detail panel

packages/core-data/src/components/Input.js, packages/core-data/src/components/Slider.js, packages/storybook/src/core-data/Slider.stories.js
This PR adds the Slider component to the Core Data package.
It's very similar to the existing `RangeSlider`, and the main difference is the input fields that allow the user to type in a value. This required handling some edge cases, as shown in the recording below.
* when a value is out of range, we reset it to the nearest in-range value (i.e. min or max)
* when the user enters a value that changes the order of the two range values (e.g. going from `[0, 100]` to `[101, 100]`), we reverse the range array so the lower value comes first (this keeps the behavior consistent with the fact that you could already reverse the range array by dragging a slider past the other slider)
* when both values are equal, we add or remove 1 from one of the values in a way that's consistent with the range …
=> Core Data Places `Slider` component

packages/core-data/src/components/SearchList.js, packages/core-data/src/components/SearchListItem.js, packages/core-data/src/i18n/en.json, packages/core-data/src/types/SearchList.js, packages/storybook/src/core-data/SearchList.stories.js
This PR adds the SearchList component from #335 
The component takes a list of items and a list of attributes to show. Attributes can be given an `icon` property. If left off, a bullet point will be shown as the icon.
The search list will expand to fit the height and width of its container, but the interior `ul` will scroll on the Y axis for overflow.
=> Core Data Places `SearchList` component

packages/core-data/src/components/Pill.js, packages/storybook/src/core-data/Pill.stories.js
This PR updates the Pill component to remove the color props and use a generic `className` prop instead.
The three relevant classes are `bg-*`, `text-*`, and `fill-*`, but this change will also allow consuming applications to add any other styles to the pill too.
=> Use `className` prop for `Pill` colors

packages/core-data/src/components/AccordionItemsList.js, packages/core-data/src/components/RecordDetailPanel.js, packages/core-data/src/index.js, packages/core-data/src/types/RelatedRecord.js, packages/core-data/src/types/RelatedRecordsList.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js
Adds the record detail panel component as an export to the `core-data` library. See https://www.figma.com/design/5AWa1c3pJeVXwEeVPbRqZj/Place-Components-2.0?node-id=85-3981&m=dev
Note: Should be merged after PR #359 .
=> Adding the record detail panel

packages/core-data/src/components/SearchList.js, packages/storybook/src/core-data/SearchList.stories.js
This PR adds a new prop called `itemTitle` to the `SearchList` component that allows the consuming application to configure how item titles are rendered.
It can be a string or a function. If it's a string, the title will be rendered by accessing that property on the item (`item[props.itemTitle]`). If it's a function, it will be run with the item as an argument (`props.itemTitle(item)`).
=> Add `itemTitle` prop for SearchList

packages/core-data/tailwind.config.js
This PR renames the `inter` font family in the Tailwind config to `sans`, which will make it the default font across all Tailwind-based components in `core-data`.
Storybook is still importing some Semantic UI styles that override Tailwind, but I can see in the dev tools that the components would be displaying Inter if not for that. So I expect this PR to fix the font issue for consuming applications, if not for Storybook.
=> Set Inter as the default font for Core Data components

packages/core-data/src/components/Pill.js, packages/storybook/src/core-data/Pill.stories.js
This PR adds `primary` and `secondary` boolean props to the Pill component to make its API consistent with the Button component.
By default, the pill now has a white background and a `secondary` border. When `primary` is true, the background is Tailwind's primary color and the text/icon are white. When `secondary` is true, the background is the Tailwind secondary color and the text/icon remain white.
This does not replace the `className` prop for custom styling.
=> Add `primary` and `secondary` props to Pill

packages/core-data/src/components/Checkbox.js
In https://github.com/performant-software/react-components/pull/363/files#diff-2a3cce7201f63050cd7c3cc94ef3679474c75b5e680d68313aa859c4e171749d, I noticed that the checkboxes in Figma were actually SVGs, rather than just a check icon with CSS styling around it. In that PR, I brought those SVGs into our `Icon` component.
This PR migrates the `Checkbox` component over to being based on the icons, too. This simplifies the styling and should fix #374.
=> Replace Radix UI icon in `Checkbox` with our checkbox SVGs

packages/core-data/src/components/AccordionItemsList.js, packages/core-data/src/components/RecordDetailPanel.js, packages/core-data/src/types/RelatedRecord.js, packages/core-data/src/types/RelatedRecordsList.js, packages/storybook/src/core-data/AccordionItemsList.stories.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js
Pursuant to Issue #373 , this PR does two things:
- Moves the `count` prop to the top level of the component rather than being set per item type;
- Renames the `relations` prop to the more generic `items`.
=> Improvements to AccordionItemsList prop structure

packages/core-data/src/components/SearchList.js, packages/core-data/src/components/SearchListItem.js
This PR fixes an issue with the `SearchList` `onPointer` events where the `item` wasn't being passed as an argument to the callbacks.
=> Fix pointer events in SearchList

packages/core-data/src/components/Checkbox.js, packages/storybook/src/core-data/Checkbox.stories.js
This PR adds a new `id` prop to the `Checkbox` component that's passed down to the `RadixCheckbox.Root` component. It also adds an example to the Storybook with a really long `label` element attached via `htmlFor`.
=> `id` prop for `Checkbox`

packages/core-data/src/components/RecordDetailPanel.js
Fixes a bug where the `pt-16` class was not always correctly taking priority in the case where breadcrumb navigation is present.
=> Bug: Fix top padding on detail panel

packages/core-data/src/components/Checkbox.js, packages/storybook/src/core-data/Checkbox.stories.js
This PR adds a new, required `ariaLabel` prop to the Core Data `Checkbox` component. The `aria-label` will be provided to the `<button>` that Radix UI uses internally to render the checkbox.
(I tried to rebuild the component with a native `<input>` element as per https://github.com/performant-software/react-components/issues/396#issuecomment-2663333271 but it was too complicated that way)
=> Add `ariaLabel` prop to Checkbox component

packages/core-data/src/components/Combobox.js, packages/core-data/src/i18n/en.json
- adds new `aria-label`s for the buttons
- changes the `Popover.Trigger` to a `Popover.Anchor` because Trigger assumed that its child would be a `<button>` was adding aria properties that aren't valid for `div`s
=> Fix a11y warnings for Combobox

packages/core-data/src/components/Checkbox.js, packages/core-data/src/components/Combobox.js, packages/core-data/src/components/Icon.js
Addresses Issue #412 by changing the default behavior of the `Icon` component to return `null` if no existing icon name is matched.
=> Update `Icon` component to return `null` if no icon matched

packages/core-data/src/components/SearchList.js, packages/core-data/src/components/SearchListItem.js
- adds a `tabIndex` value to the scrollable element to satisfy the "Ensure elements that have scrollable content are accessible by keyboard" error
- wraps the `SearchListItem` component in an `li` and changes the existing `li` to a `div`, fixing a couple errors related to the `li` not being a direct child of the `ul` when an `onItemClick` callback was used
=> SearchList a11y fixes

packages/core-data/src/components/Pagination.js, packages/core-data/src/components/SearchResultsTable.js, packages/core-data/src/i18n/en.json
- adds a `tabIndex` to the scrollable `<table>` element to make its children accessible via keyboard
- adds `aria-labels` to the buttons in the `Pagination` component
- for consistency, moves the pre-existing `rowsPerPage` i18n value to be under the `Pagination` object instead of the `SearchResultsTable` object since it's actually appearing in the `Pagination` component
=> SearchResultsTable a11y fixes

packages/core-data/src/components/Input.js, packages/core-data/src/components/Slider.js, packages/core-data/src/i18n/en.json
* adds `aria-label` attributes to the input elements in Slider
* updates the `Input` component to accept a new, optional `ariaLabel` prop, whose value is applied as `aria-label` to the `<input>` element
=> Slider a11y fixes

packages/core-data/src/components/Input.js, packages/storybook/src/core-data/Input.stories.js
This PR fixes an issue where the `position` of the clear button in the Core Data `Input` component was set to `absolute`, causing it to float to the right edge of the page, outside the component.
* change it to be relative positioned
* add a new Storybook story to handle this case, as the bug went unnoticed here because existing ones all filled the width of their pages
=> Fix position of clear button on Input

packages/core-data/src/components/SearchResultsTable.js
This PR removes the `whitespace-no-wrap` CSS rule from the Core Data `SearchResultsTable` component, allowing the table to dynamically adjust column widths depending on the data inside it.
=> Remove `whitespace-no-wrap` from SearchResultsTable

packages/core-data/src/components/Slider.js, packages/storybook/src/core-data/Slider.stories.js
This PR addresses the following bits of feedback from #423:
* padding removed from the top-level container div
* added a new `classNames` value called `container` to style the container div (`root` was already taken by the actual Radix Slider's root component)
* changed the dark colors throughout the component to `neutral-800`
=> Slider improvements

packages/core-data/src/components/RecordDetailHeader.js, packages/core-data/src/i18n/en.json, packages/storybook/src/core-data/RecordDetailHeader.stories.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js
Limits the height of the text content in the `RecordPanelHeader` component to six lines and displays a `Show More` button in the case that this limit is exceeded, which expands the container to show the full text content. 
- I chose six lines a bit arbitrarily based on what looked reasonable to me, but of course open to tweaks.
=> Adds line limit and Show More button to `RecordPanelHeader`

packages/core-data/src/components/SelectRecordPanel.js, packages/core-data/src/i18n/en.json, packages/storybook/.storybook/main.js, packages/storybook/.storybook/preview.js, packages/storybook/package.json, packages/storybook/src/core-data/SelectRecordPanel.stories.js, yarn.lock
This PR includes the `SelectRecordPanel` component from #336. It expands to the height and width of its parent and accepts a list of items with a `renderTitle` callback to get the names to display in the list.
This PR also adds the Storybook background addon and configures a dark mode, which makes it easier to showcase components that have white backgrounds and no borders, like this one. It doesn't affect existing stories but allows us to use a darker background on a per-story basis.
=> Core Data Places `SelectRecordPanel`

packages/core-data/src/components/Checkbox.js, packages/storybook/src/core-data/Checkbox.stories.js
- adds a new `hover:bg-transparent` class to the Checkbox's root component to override the Peripleo CSS rule that was causing the gray background on hover
- adds a new `className` prop to allow consuming applications to style the Checkbox
- removes an extraneous `hover:bg-white` class from the SVG that was left over from the previous version of the component
=> Fix checkbox styling

packages/core-data/src/components/LayerMenu.js
Per performant-software/core-data-places#52:
- Set data layers marked `default` (via config.json/using tina) to be visible by default
I'd attempted to do this entirely within CDP code, but because the initial `selectedOverlays` state in this component was set to `{}`, and there is a `useEffect` here that checks for that state's change and then calls the `props.onChangeOverlays` callback, the selected overlays were always getting reset back to nothing on mount. Rather than trying to divine when this component mounts and handle it externally, I figured it makes more sense to check for the `default` layers and set the initial state here.
Also just learned about `_.chain` from your CDP PR, Derek, so useful!
=> Set default data layers as initial selected state (CDP #52)

packages/core-data/src/components/SearchList.js, packages/core-data/src/components/SearchListItem.js, packages/core-data/src/components/SearchResultsTable.js, packages/storybook/src/core-data/SearchList.stories.js, packages/storybook/src/core-data/SearchResultsTable.stories.js
This PR adds a new `isHighlight` callback prop to `SearchList` and `SearchResultsTable`. If provided, each item will be passed through the function and will be rendered with a `bg-neutral-200` if the function returns `true`.
The appearance of a highlighted (highlit?) item is identical to the hover appearance of clickable items. `isHighlight` and `onClick` can be used together.
=> Controlled item highlight for `SearchList` and `SearchResultsTable`

packages/core-data/src/components/AccordionItemsList.js, packages/core-data/src/types/RelatedRecordsList.js, packages/storybook/src/core-data/AccordionItemsList.stories.js
Addressing Issue #431 by adding an optional `horizontal` flag for each item in an accordion list, which allows the content to be displayed in a horizontal row rather than a column.
=> Adds optional horizontal setting for accordion sections

packages/core-data/src/components/SearchListItem.js, packages/storybook/src/core-data/SearchList.stories.js
This PR fixes a couple issues with the SearchList component:
* makes the button hover background consistent with the highlight background (`bg-neutral-200` - originally they were subtly different shades of gray)
* moves the `bg-neutral-200` class for highlighted and hovered items to the top-level `li` element instead of the inner `div`, so any extra styles applied to elements inside the component won't interfere with the background color (https://github.com/performant-software/react-components/issues/439 was caused by some padding added to `button` elements by one of CDP's stylesheets)
=> Fix SearchList highlight/hover behavior

packages/core-data/src/components/Icon.js
Addresses Issue #429 by adding the `flex-shrink-0` class to the `Icon` component so that it isn't squished when e.g. the title of a record detail panel is extra long.
=> Fixing unpredictable icon resizing

packages/core-data/src/components/RecordDetailHeader.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js
Pursuant to Issue #444 , fixes an unmount bug stemming from the resize observer in the `RecordDetailHeader` component.
Note that for now I left in the Storybook component that I used to test the functionality, in case that's useful for review and testing; possibly it should be removed before merging, since it's not really necessary to include in Storybook once we're satisfied that it's working.
=> Fixing unmount bug with `RecordDetailHeader`

packages/core-data/src/components/PersistentSearchStateContextProvider.js, packages/core-data/src/components/SearchResultsLayer.js, packages/core-data/src/hooks/ProgressiveSearch.js, packages/core-data/src/hooks/Typesense.js, packages/core-data/src/index.js
This pull request makes the following changes in support of https://github.com/performant-software/core-data-places/issues/68, which allows for the bounding box of the map to be adjusted as the layout changes. Previously, we were only adjusting the map bounding box on search.
- Fixes a bug with `isFirstPage` and `isLastPage` in `ProgressiveSearch`. There were situations where the `results` object did not contain `nbResults`, so `isLastPage` was always evaluating to "false", leading to Typesense making requests for pages that did not exist. We've updated the component to use the `isFirstPage` and `isLastPage` values that are provided by `infiniteHits`.
- Adds the `searching` property to the `ProgressiveSearch` state. This can be used to determine if we're currently making requests to the …
=> CDP #68 - Bounding box

packages/core-data/src/components/SearchList.js, packages/storybook/src/core-data/SearchList.stories.js
This PR updates `SearchList` to only show 50 items in the list by default. When the user scrolls 80% of the way down the list, the next 50 items will be displayed, and so on until we're showing the entire list. The feature is pretty minimalist, just some event listeners on the parent `<ul>` component, so there's plenty of room to tweak the values if it feels off.
It also includes a new Storybook story with 1250 list items to test out performance.
(`react-window` wasn't an option for this fix because it expects list items to be a consistent, hardcoded size.)
=> Smarter item rendering for `SearchList`

packages/core-data/src/components/Combobox.js, packages/storybook/src/core-data/Combobox.stories.js
This pull request makes the following changes to the `Combobox` component:
- Adds the `classname` prop to allow the root element to be styled by the consumer; Removes hard-coded padding
- Fixes an issue with the way the `isSelected` callback was constructed
- Places options and selected value elements inside a `span` tag and applies left text alignment
It also makes the following adjustments to allow the component to be placed into a container with less horizontal space:
- Removes the padding/hover background from clear all and dropdown buttons
- Updates text sizes to `text-sm` and `text-xs` on options and selected values
=> RC #450 - Combobox

packages/core-data/src/components/SearchList.js, packages/storybook/src/core-data/SearchList.stories.js
This PR fixes an issue with `SearchList` where the `onScroll` function from #451 based its calculations on the initial version of `props.items` passed down from its parent. When the initial version was an empty array, the loading wouldn't work.
* add `props.items` as a dependency to the `onScroll` callback function
* remove and then re-add the `onScroll` function to the `<ul>`'s event listener each time `props.items` changes
* update the "Huge Amount of Data" Storybook example to use a 500ms timeout before setting its `items` array, as a test case for this bug
=> Fix `SearchList` item loading when initialized with empty `props.items` array

packages/core-data/src/components/SearchListItem.js
This PR updates `SearchListItem` based on feedback in #456:
* use `bg-primary/20` for the highlight and hover states
* reduce horizontal padding
=> SearchListItem adjustments

packages/core-data/src/components/SearchResultsTable.js
This PR changes the highlight color for selected rows in `SearchResultsTable` from `neutral-200` to `primary/20`.
=> Use primary color highlight for `SearchResultsTable`

packages/core-data/src/components/SearchList.js
Previously, `SearchList` was checking for `props.items.length >= oldLimit + LIMIT_STEP` when determining whether to raise the limit. This prevented the last page from loading if the number of items was not divisible by 50.
This PR simplifies that check to `props.items.length > oldLimit`, which will correctly load the last page.
=> Fix`SearchList` not loading last group of items

packages/core-data/src/components/AccordionItemsList.js, packages/core-data/src/components/RecordDetailPanel.js, packages/core-data/src/components/RecordDetailTitle.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js, packages/storybook/src/core-data/RecordDetailTitle.stories.js
Addresses the issues described in Issue #455:
- Removes the drop shadow from the related items accordion list. Note: I spent some time trying to research how to have a drop shadow effect on the sides of an element and not the bottom and it sounded either extremely complicated or impossible, although I may be missing something. I think the cleanest solution here is to add the shadow to the entire containing element in the map search layout in `core-data-places` if we want it along the sides of that column.
- Removes the shadow entirely if there are no related items
- Changes the icon alignment in the title to the top
- Updates the border color to `neutral-200` in the related items list
- Adds the `bg-white` class to the `AccordionItemsList` component
=> `RecordDetailPanel` design fixes

packages/core-data/src/components/SearchList.js, packages/core-data/src/components/SearchListItem.js
* replaces the scroll event listener logic in `SearchList` with the `InfiniteScroll` component
* changes the `<ul>` and `<li>` elements in `SearchList` to `div`s because `InfiniteScroll` inserts a `div` between the two layers that will cause accessibility warnings
* not sure how to feel about this - it's more semantic (and therefore more accessible) to use list elements to display a list. This feels like another case where we're trying to satisfy warnings on a piecemeal basis without looking at the big picture. But keeping a semantic list would require some breaking changes to `InfiniteScroll` and I'm not sure what exactly those changes would look like.
=> Migrate SearchList to InfiniteScroll

packages/core-data/src/components/RecordDetailContent.js, packages/core-data/src/components/RecordDetailHeader.js, packages/core-data/src/components/RecordDetailPanel.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js
This pull request updates the `RecordDetailPanel` component to allow the "Show More" button to apply to the entire middle contents of the component. A `RecordDetailContent` component has been added to encompass the show/hide logic and all of the content that will be rendered. Additionally, the `RecordDetailHeader` component was refactored to display on the breadcrumbs, title, and close button.
The initial view with additional content to be displayed.
The view when the "Show More" button is clicked.
The view scrolling down to the bottom of the component.
Screenshot from testing within Core Data Places.
=> RC #470 - Record detail panel

packages/core-data/package.json, packages/core-data/src/index.js, packages/core-data/src/ssr.js, packages/core-data/vite.config.js
* adds a new file to the `core-data` package called `ssr.js`. `ssr.js` mirrors the contents of `index.js`, but anything that requires browser APIs is omitted
* updates the Vite config and `package.json` to allow consuming applications to import the SSR-safe version of the package via `@performant-software/core-data/ssr`
The standard package imported via `@performant-software/core-data` is unchanged, so this PR does not contain any breaking changes.
The Core Data model services are exported by `ssr.js` so #393 should be unblocked.
=> Add `ssr` export to Core Data package

packages/core-data/package.json, packages/core-data/src/components/SearchResultsLayer.js, packages/core-data/src/utils/Typesense.js, packages/geospatial/package.json, packages/geospatial/src/components/LocationMarkers.js
This pull request makes the following changes to support [#139](https://github.com/performant-software/core-data-places/issues/139) and making clustering less brittle.
- Upgrades the Peripleo peer dependency to the latest version
- Updates `SearchResultsLayer` to accept a `data` prop instead of using `useCachedHits` hook
- This will allow data to be transformed before it is added to the map
- Updates `toFeatureCollection` to allow filtering geometries by "type"
- Adds the `interactive` prop to `LocationMarkers`
=> CDP #139 - Map clustering

packages/core-data/src/components/Button.js, packages/storybook/src/core-data/Button.stories.js
Per https://github.com/performant-software/core-data-places/issues/116:
- Per [designs](https://www.figma.com/design/5AWa1c3pJeVXwEeVPbRqZj/Place-Components-2.0?node-id=15-9790&t=xAKdjWVT7HJmFM0A-4), add `bg-white` to default button state
- Timeline button and Table button: one must be disabled when the other is enabled, so add `disabled` prop and style for button, per designs
- Apply a transparent border across all `primary` buttons to ensure size consistency. (I noticed that an `icon` button can cause content to shift when `primary` is enabled or disabled, due to the border changing)
=> Button style and props tweaks (CDP #116)

packages/core-data/src/components/Button.js, packages/core-data/src/components/FacetTimeline.js, packages/core-data/src/components/Modal.js, packages/core-data/src/utils/Peripleo.js, packages/storybook/src/core-data/FacetTimeline.stories.js
Per https://github.com/performant-software/core-data-places/issues/116:
- Update `FacetTimeline` to use Typesense formatted data, instead of hitting a Core Data API endpoint
- Prevent timeline from showing out-of-bounds events during update
- Simplify functions to ensure full faceted date range is represented on the timeline
- Fix bug with event width/height on the timeline (was not accounting for `rem` size)
- Use `ButtonGroup` for zoom buttons, ensure `disabled` button always gets a border (was causing the zoom buttons to reflow content)
- Adjust `Modal` to always be at `z-50` z-index (we have some z-index stuff in the timeline that a `Modal` should always supersede)
Other:
- Fix a typo in the runtime config normalizer for typesense
=> Timeline revisions (CDC #116)

packages/shared/package.json
This PR adds `"type": "module"` to `shared-components`'s `package.json`. This field is already present in the other packages, and its absence caused errors when importing it in a Node context.
I tested with a beta release and this change doesn't seem to have broken anything on the browser side.
=> Add `"type": "module"` to `shared-components`

packages/core-data/src/utils/Typesense.js, packages/shared/src/utils/Object.js
- updates `toFeatureCollection` to remove nested geometry fields (along with stripping the Typesense metadata fields `_rawTypesenseHit`, `_snippetResult`, and `_highlightResult`, which duplicate the geometry data) to drastically reduce the amount of data we send to Peripleo, improving performance when the search results contain polygons
- adds a new `setNestedValue` helper function to `ObjectUtils` inspired by `getNestedValue` that allows updating a value based on a string path, e.g. `setNestedValue(myObject, 'item.myArray[2].title', 'new title')`.
=> Remove `geometry` fields from `toFeatureCollection`

packages/geospatial/src/components/LocationMarkers.js
This pull request updates the `LocationMarkers` component to use the `useLoadedMap` hook instead of `useMap`. The difference here is that `useLoadedMap` will return `undefined` until the map is loaded. This will allow the effect that sets the bounding box to run after the map has full loaded.
=> CDP #145 - Map Zoom

packages/core-data/src/components/FacetTimeline.js
Per performant-software/core-data-places#165:
- Remove unnecessary border between grouped buttons (this still seems to be slightly inconsistent between storybook and CDP, but I think this version works well on CDP)
Other:
- Fix an issue where the markers were incorrectly offset from the timeline, due to an inconsistency in font `rem` size between storybook and CDP
- Set the slider color to use a `primary` variant instead of `slate`
=> Adjust timeline styles (CDP #165)

packages/core-data/src/utils/Typesense.js
The `toFeatureCollection` changes from #483 caused an error when `geometry` was a top-level field (i.e. when we're indexing places directly, instead of another model with related places). In this case, we don't actually want to modify the result item at all. This PR fixes the error and updates the logic so it doesn't touch top-level places.
=> Update `toFeatureCollection` to handle records with no nested geometry

packages/core-data/src/components/RecordDetailPanel.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js
* adds a new `coverUrl` prop to `RecordDetailPanel`. When provided, the component will display the image above the header
* the image is set to a height of 220px (the exact pixel measurement from Figma) and 100% width, with `object-fit: cover` so it will zoom to fill the space. This means that every image takes up a consistent amount of space in the component and it allows us to hardcode the `img` element's height, avoiding layout shifts when it loads in.
* adds new conditional styling to the close button to use a rounded black background when a cover image is present
=> Cover images for search panels

packages/core-data/package.json, packages/core-data/src/components/MediaGallery.js, packages/core-data/src/i18n/en.json, packages/storybook/.storybook/api/core-data/Manifests.js, packages/storybook/.storybook/routes/CoreData.js, packages/storybook/src/core-data/MediaGallery.stories.js, yarn.lock
Per performant-software/iiif-cloud#90:
- Use the Plugins feature, introduced in Clover IIIF viewer v2.9, to show canvas-level metadata as introduced by https://github.com/performant-software/iiif-cloud/pull/92 in the `MediaGallery` component
- I ended up not using the `Metadata` primitive as that just created unstyled `dl`, `dt`, `dd`, which we can't easily apply Tailwind styles to as they aren't exposed. I figured I would just replicate its internal structure in order to apply those styles in a normal way.
- In Storybook I had to pass the real manifest URL along to the manifest for its `id` property for Clover IIIF Viewer 2.4+, as it just hangs without error if this URL doesn't resolve to the manifest. It also doesn't accept relative URLs, due to its reliance on [this …
=> Display canvas-level metadata in MediaGallery (IIIF Cloud #90)

packages/core-data/package.json, yarn.lock
- Downgrade Clover IIIF to v2.9.1 due to an issue with newer versions that requires a IIIF manifest URL to match its `id` property
- Tested on CDP locally with a beta release.
- I left the storybook fixture fix in place, such that its manifest ID does match its request URL, just so it behaves more like a typical IIIF manifest.
=> Downgrade Clover IIIF viewer to v2.9.1

packages/core-data/src/components/SearchResultsTable.js
This pull request fixes a bug where the `SearchResultsTable` component was not properly scrolling with the results, only the first 5 results were visible.
The solution was to remove an outer `div` element and add the `overflow-auto` class to the table container `div`.
=> CDP #201 - Table scroll

packages/core-data/src/components/RecordDetailPanel.js, packages/storybook/src/core-data/RecordDetailPanel.stories.js
Updates the styling of the breadcrumbs in the `RecordDetailPanel` to take into account whether or not there's a cover image, and to appear below the image if so.
=> Adding compatibility between breadcrumbs and cover img

.vscode/settings.json, eslint.config.js, package.json, yarn.lock
This PR addresses an issue where some of the stylistic linting rules were silently broken after the ESLint 9 upgrade.
I installed `@stylistic/eslint-plugin` on the recommendation of the ESLint developers and prefixed the affected rules in the ESLint config file with `@stylistic`.
That was enough to get most of them working, but I noticed I still wasn't getting red squigglies for missing semicolons. The config file didn't have anything set up to require semicolons, so I guess that rule came built-in with older versions of ESLint. I added the `@stylistic/semi` rule to fix that issue, but it wouldn't surprise me if some other rules might have slipped through the cracks.
It's also likely that some configuration will be required on the `tailwind-ui` branch, but that should happen on that …
=> Fix linting with ESLint 9

eslint.config.js, package.json, packages/storybook/src/tailwind-ui/Input.stories.tsx, packages/tailwind-ui/src/components/Input.tsx, yarn.lock
This PR extends on the changes in #532 for the `tailwind-ui` branch.
* refactor the ESLint config so rules shared by both the JS and TS linters are in a `commonRules` object that both linters can extend (previously the TS linter just had most of the same rules copy/pasted)
* add `eslint-import-resolver-typescript` so the `import-x/no-unresolved` doesn't happen for TSX component imports
* lint the `Input` component and its Storybook story
=> Linting config for TS files

packages/storybook/src/tailwind-ui/Badge.stories.tsx, packages/tailwind-ui/src/components/Badge.tsx
This PR adds the `Badge` component to the `tailwind-ui` package.
It accepts a `color` prop for one of a set of five colors. The design in Figma has a lot more, but I think they came from Catalyst so we can't use the same exact list. I focused on generic versions of colors that appear in the FCC 2 UI.
=> Tailwind `Badge` component

packages/storybook/src/tailwind-ui/Checkbox.stories.tsx, packages/tailwind-ui/package.json, packages/tailwind-ui/src/components/Checkbox.tsx, packages/tailwind-ui/tailwind.css
This PR includes the `Checkbox` component for `tailwind-ui`. It's built with `@headlessui/react`'s Checkbox component.
This is the first of my component PRs to not include a dark theme. We decided today to skip it to save time.
=> Tailwind `Checkbox` component

packages/storybook/src/tailwind-ui/Listbox.stories.tsx, packages/tailwind-ui/src/components/Listbox.tsx, packages/tailwind-ui/src/index.ts
This PR adds the Listbox component to `tailwind-ui`.
As before, I skipped the pieces from Figma that do not appear in FCC 2, which turned this into a pretty simple component.
=> Tailwind `Listbox` component

packages/storybook/src/tailwind-ui/Dialog.stories.tsx, packages/tailwind-ui/src/components/Dialog.tsx, packages/tailwind-ui/src/index.ts
This PR contains the `Dialog` component for Performant UI.
As with Card, I ended up paring down the API to just be a really minimal wrapper around Headless UI's `Dialog` with some basic Tailwind classes.
In the future we might want to expand it to have built-in positioning for a title or a bottom button bar, but FCC 2 has enough variations that nothing stood out to bake into the component.
=> Performant UI `Dialog` component

packages/performant-ui/src/components/MediaSelect.tsx, packages/performant-ui/src/index.ts, packages/storybook/src/performant-ui/MediaSelect.stories.tsx
This PR adds the MediaSelect component to Performant UI.
Some caveats:
* The components expects the consuming application to handle state - this component passes up the native `FileList` value from the `<input>`.
* The trash can button to remove a file is only rendered only if the parent component passes an `onRemoveFile` prop, because working with the native `FileList` interface is tricky (it's read-only, so you have to come up with some sort of indirect technique) and because FCC 2 will only need the single-file version of this component.
* I did not include the thumbnails that are present in the Figma design. This, again, is kind of tricky (probably some sort of `createObjectURL` thing with some cleanup for when files are removed) and we need to save time.
* There's a high chance that …
=> Performant UI `MediaSelect` component

packages/performant-ui/src/components/Table.tsx, packages/performant-ui/src/index.ts, packages/storybook/src/performant-ui/Table.stories.tsx
This PR adds the Table component to Performant UI. It uses the subcomponent model similar to #525, with e.g. `Table.Head`, `Table.Row`, etc.
As with #549, some caveats vs. the Figma designs:
* The component in Figma has a couple visual modes (striped and grid) that are not used in FCC 2. To save time, I only built the default mode that appears in the FCC 2 designs.
* The Figma designs have a lot of variations with dropdowns, avatars, etc. that do not need to be handled by the component, as the `Table.Cell` subcomponent just renders whatever is passed as `props.children` inside a styled `td` element.
* This component does not contain the Pagination component inside it the way it's shown in the designs. It seems more ergonomic to have the consuming application add the Pagination component …
=> Performant UI `Table` component
